language: node_js
sudo: required
dist: trusty
node_js:
  - '5.4.1'

addons:
  apt:
    packages:
      - g++

cache:
  directories:
    - node_modules
    - typings

install:
  - ./tools/ci/install.sh

script:
  - ./tools/ci/test.sh
